# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Program"
  url = "/program"
  weight = 10

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 20  
  
[[main]]
  name = "Become a Mentor"
  url = "/mentor"
  weight = 30

[[main]]
  name = "Info"
  identifier = "info"
  url = "/info"
  weight = 40
  
[[main]]
name = "Orga team"
parent = "info"
identifier = "info1"
url =  "/team"

[[main]]
name = "Website contributions"
parent = "info"
identifier = "info2"
url =  "/info"