baseURL = "https://GeoXautumnSchool2020.netlify.com/"
languageCode = "en-us"
title = "Autumn School 2020"
description = ""
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Simeon Lisovski"
    description = ""
    logo = "GeoX_logo.png"
    twitterAuthor = "@Geo_X_"
    githubUsername = "slisovski"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = []

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Start"
    weight = 1
    
[[menu.main]]
    url = "/"
    name = "Program"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Research projects"
    weight = 3

[[menu.main]]
    url = "/mentors/become_a_mentor"
    name = "Become a mentor"
    weight = 4
    

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://www.facebook.com/GeoXEarlyCareers/"
    name = "fab fa-facebook"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/@Geo_X_/"
    name = "fab fa-twitter"
    weight = 2
