---
aliases: [up-and-running-with-blogdown]
title: Website contributions
authors: [Simeon]
date: '2020-09-28'
tags: [blogdown]
categories:
  - Rstudio
  - blogdown
  - hugo
  - netlify
summary: A guide to getting up and running with blogdown, GitHub, and RStudio
image:
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE, collapse = TRUE, comment = NA, tidy = FALSE)
```

This website is made with [github](https://github.com/slisovski/GeoX_autumnSchool2020), the [blogdown](https://bookdown.org/yihui/blogdown/) R package, and the Academic theme for [Hugo](https://themes.gohugo.io/academic/).

There are many ways to edit this website. I consider the _R Studio_ way the easiest. So, if you want to edit your research challange or contribute to the website, the information below will (hopefully) help you getting up and running with R blogdown and our Autumn School 2020 website.

# Read up on blogdown

Before you start, you may want to have some background information:

* [`blogdown`: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) by Yihui Xie and Amber Thomas
* [Making a Website Using `blogdown`, Hugo, and GitHub pages](http://amber.rbind.io/blog/2016/12/19/creatingsite/) also by Amber Thomas


# Setup

You need to have R and RStudio installed (make sure to have a recent version > 3.4).

- Create a github account [here](https://github.com/).
- Ask Simeon ([simeon.lisovski@gmail.com](mailto:simeon.lisovski@gmail.com)) to be added as a collaborator to the repo.

# In R Studio

- Go to File -> New Project
- Select, _Version Control_ -> _Git_
- Copy paste `https://github.com/slisovski/GeoX_autumnSchool2020` into the Repository URL box, change the directory if nessesary and press _Create Project_.

R studio will pull the entire website directory into the specified path.

The important folder within the directory is the `content` folder:

```
...
├── content
│   ├── home
│   ├── info
│   ├── mentor
│   ├── program
│   ├── project
│   └── projects
...
```

- `content`: contains .md or .Rmd files used to render the page 
	+ `home`: all sites displayed on the first page 
	+ `info`: this site 
	+ `mentor`: the become a mentor site
	+ `program`: the program site
	+ `project`: the project folders
	+ `projects`: widget for project site
	
## Change your project site

You can now start and open e.g. your research project site, make changes etc. Once you are finished, you can comit your changes via the _Git_ window in R Studio. Here, you will see, all files that you changed. Select the one you want to push to the respository and to the website, provide some information on your changes and press commit. The final step is to _Push_ your commits.

To avoid conflicts between pushes from several people working on the very same document. You can create a _New Branch_ in the git window. Give it a sensible name (e.g. your username) and commit as well as push all changes into this branch. I will keep track of these changes and merge them into the masater branch.

If you have any questions, feel free to ask!


# Caveats, disclaimers, etc.

Even with all the resources listed above, getting up and running takes a few tries. Here are some additional places to get started:

* For Git: [Happy Git with R](http://happygitwithr.com) by Jenny Bryan et al.
* For RStudio: [DataCamp's Working with the RStudio IDE (free)](https://www.datacamp.com/courses/working-with-the-rstudio-ide-part-1) by Garrett Grolemund

On a mac you may also need [Xcode](https://developer.apple.com/xcode/) and [Homebrew](https://brew.sh) installed- [you will probably need these to download Hugo](https://bookdown.org/yihui/blogdown/installation.html). If you don't have either but are on a mac, this link may help:

* [How to install Xcode, Homebrew, Git, RVM, Ruby & Rails on Mac OS X ](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/)


